[package]
name = "systemctl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "systemctl"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = { version = "1.0"}
libc = "0.2"